const API="https://game-image-cloud-tool.genikid-ai.chatgpt.site/api/upload";
const GOOGLE_CLIENT_ID="1046636346751-eerb64n25k8ro8t72dd7588llnp0ojqv.apps.googleusercontent.com";
const folder=document.querySelector("#folder"),input=document.querySelector("#images"),drop=document.querySelector(".drop"),filesBox=document.querySelector("#files"),error=document.querySelector("#error"),upload=document.querySelector("#upload"),results=document.querySelector("#results"),list=document.querySelector("#result-list");
let files=[],uploaded=[],credential="";
function loginState(state){const box=document.querySelector("#login-box"),status=document.querySelector("#login-status"),help=document.querySelector("#login-help"),content=document.querySelector("#tool-content");box.classList.remove("success","failed");content.hidden=state!=="success";if(state!=="success")results.hidden=true;if(state==="success"){box.classList.add("success");status.textContent="登入成功";help.textContent="可以開始上傳圖片"}else if(state==="failed"){box.classList.add("failed");status.textContent="登入失敗";help.textContent="這個帳號沒有使用權限，請改用已授權帳號。"}else{status.textContent="請先登入 Google";help.textContent="登入後才能上傳圖片"}}
function startGoogle(){if(!window.google)return setTimeout(startGoogle,100);google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:async r=>{try{const response=await fetch(API.replace("/upload","/auth/verify"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({credential:r.credential})});const result=await response.json();if(!response.ok||!result.ok)throw new Error();credential=r.credential;loginState("success");document.querySelector("#google-signin").hidden=true;document.querySelector("#google-signout").hidden=false}catch{credential="";loginState("failed")}}});google.accounts.id.renderButton(document.querySelector("#google-signin"),{theme:"outline",size:"large",text:"signin_with",locale:"zh_TW"})}startGoogle();
document.querySelector("#google-signout").addEventListener("click",()=>{google.accounts.id.disableAutoSelect();credential="";loginState("idle");document.querySelector("#google-signin").hidden=false;document.querySelector("#google-signout").hidden=true});
function safeFolder(value){const ascii=value.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(ascii)return ascii.slice(0,48);let hash=2166136261;for(const char of value){hash^=char.codePointAt(0)||0;hash=Math.imul(hash,16777619)}return`game-folder-${(hash>>>0).toString(36)}`}
folder.addEventListener("input",()=>document.querySelector("#path").textContent=`images/${folder.value.trim()?safeFolder(folder.value.trim()):"game-folder"}/`);
function addFiles(incoming){const images=[...incoming].filter(f=>f.type.startsWith("image/"));if(!images.length)return showError("請加入 JPG、PNG、WebP 或 GIF 圖片。");files=[...files,...images].slice(0,20);error.hidden=true;filesBox.innerHTML=files.map(f=>`<div class="file"><b>${escapeHtml(f.name)}</b><span>${Math.max(1,Math.round(f.size/1024))} KB</span></div>`).join("")}
input.addEventListener("change",()=>{addFiles(input.files);input.value=""});
["dragenter","dragover"].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();e.stopPropagation();drop.classList.add("dragging")}));
["dragleave","drop"].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();e.stopPropagation();drop.classList.remove("dragging")}));
drop.addEventListener("drop",e=>addFiles(e.dataTransfer.files));
document.addEventListener("dragover",e=>e.preventDefault());
document.addEventListener("drop",e=>{if(!drop.contains(e.target))e.preventDefault()});
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function imageDescription(name){const base=name.replace(/\.[^.]+$/,'');const chinese=base.match(/[\u3400-\u9fff]+/g);return chinese?.join('、')||base.replace(/^\d+[\s._-]*/,'').replace(/[_-]+/g,' ').trim()||'圖片'}
function showError(message){error.textContent=message;error.hidden=false}
upload.addEventListener("click",async()=>{if(!credential)return showError("請先使用已授權的 Google 帳號登入。");if(!folder.value.trim())return showError("請先輸入雲端資料夾名稱。");if(!files.length)return showError("請至少加入一張圖片。");error.hidden=true;upload.disabled=true;uploaded=[];try{for(let i=0;i<files.length;i++){const file=files[i];upload.textContent=`正在上傳 ${i+1}／${files.length}…`;const body=new FormData();body.append("folder",folder.value.trim());body.append("credential",credential);body.append("images",file);const response=await fetch(API,{method:"POST",body});const type=response.headers.get("content-type")||"";if(!type.includes("application/json"))throw new Error("Google 登入驗證服務尚未啟用，請稍後再試。");const data=await response.json();if(!response.ok||!data.images)throw new Error(`${file.name}：${data.error||"上傳失敗"}`);uploaded.push(...data.images);renderResults()}files=[];input.value="";filesBox.innerHTML=""}catch(e){showError(e.message||"上傳失敗，請稍後再試。")}finally{upload.disabled=false;upload.innerHTML="上傳並產生網址 <span>→</span>"}});
function renderResults(){results.hidden=false;list.innerHTML=uploaded.map(x=>`<article class="result-row"><img src="${x.url}" alt=""><div><b>${escapeHtml(imageDescription(x.name))}</b><a href="${x.url}" target="_blank" rel="noopener">${x.url}</a><div class="badges"><span class="${x.github}">GitHub ${x.github==="success"?"已發布":"失敗"}</span><span class="${x.drive}">Google ${x.drive==="success"?"已備份":"失敗"}</span></div></div><button data-url="${x.url}">複製網址</button></article>`).join("");results.scrollIntoView({behavior:"smooth"})}
function copyWithFeedback(button,text){navigator.clipboard.writeText(text);const label=button.textContent;button.textContent="已複製";setTimeout(()=>button.textContent=label,1600)}
list.addEventListener("click",e=>{const url=e.target.dataset.url;if(url)copyWithFeedback(e.target,url)});document.querySelector("#copy-all-urls").addEventListener("click",e=>copyWithFeedback(e.currentTarget,uploaded.filter(x=>x.github==="success").map(x=>x.url).join("\n")));document.querySelector("#copy-all").addEventListener("click",e=>copyWithFeedback(e.currentTarget,uploaded.filter(x=>x.github==="success").map(x=>`${imageDescription(x.name)}：${x.url}`).join("\n")));
