const API="https://game-image-cloud-tool.genikid-ai.chatgpt.site/api/upload";
const folder=document.querySelector("#folder"),input=document.querySelector("#images"),filesBox=document.querySelector("#files"),error=document.querySelector("#error"),upload=document.querySelector("#upload"),results=document.querySelector("#results"),list=document.querySelector("#result-list");
let files=[],uploaded=[];
function safeFolder(value){const ascii=value.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(ascii)return ascii.slice(0,48);let hash=2166136261;for(const char of value){hash^=char.codePointAt(0)||0;hash=Math.imul(hash,16777619)}return`game-folder-${(hash>>>0).toString(36)}`}
folder.addEventListener("input",()=>document.querySelector("#path").textContent=`images/${folder.value.trim()?safeFolder(folder.value.trim()):"game-folder"}/`);
input.addEventListener("change",()=>{files=[...input.files].filter(f=>f.type.startsWith("image/")).slice(0,20);filesBox.innerHTML=files.map(f=>`<div class="file"><b>${escapeHtml(f.name)}</b><span>${Math.max(1,Math.round(f.size/1024))} KB</span></div>`).join("")});
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function showError(message){error.textContent=message;error.hidden=false}
upload.addEventListener("click",async()=>{if(!folder.value.trim())return showError("請先輸入雲端資料夾名稱。");if(!files.length)return showError("請至少加入一張圖片。");error.hidden=true;upload.disabled=true;upload.textContent="正在上傳…";const body=new FormData();body.append("folder",folder.value.trim());files.forEach(f=>body.append("images",f));try{const response=await fetch(API,{method:"POST",body,credentials:"include"});const type=response.headers.get("content-type")||"";if(!type.includes("application/json"))throw new Error("請先點上方連結登入安全上傳服務，登入後再回來上傳。");const data=await response.json();if(!response.ok||!data.images)throw new Error(data.error||"上傳失敗");uploaded=data.images;renderResults();files=[];input.value="";filesBox.innerHTML=""}catch(e){showError(e.message||"上傳失敗，請稍後再試。")}finally{upload.disabled=false;upload.innerHTML="上傳並產生網址 <span>→</span>"}});
function renderResults(){results.hidden=false;list.innerHTML=uploaded.map(x=>`<article class="result-row"><img src="${x.url}" alt=""><div><b>${escapeHtml(x.name)}</b><a href="${x.url}" target="_blank" rel="noopener">${x.url}</a><div class="badges"><span class="${x.github}">GitHub ${x.github==="success"?"已發布":"失敗"}</span><span class="${x.drive}">Google ${x.drive==="success"?"已備份":"失敗"}</span></div></div><button data-url="${x.url}">複製網址</button></article>`).join("");results.scrollIntoView({behavior:"smooth"})}
list.addEventListener("click",e=>{const url=e.target.dataset.url;if(url){navigator.clipboard.writeText(url);e.target.textContent="已複製"}});document.querySelector("#copy-all").addEventListener("click",()=>navigator.clipboard.writeText(uploaded.filter(x=>x.github==="success").map(x=>x.url).join("\n")));
